### ISSUE TITLE
silverstripe 3.2 problem

### ISSUE THREAD

**Issue by webspilka** [nathancox/silverstripe-codeeditorfield#2]
hi
in silverstripe 3.1 everything works very well
I try install silverstripe-codeeditorfield on silverstripe 3.2-dev 
when I click on show: HTML Editor button on tinyMCE
I get next error:

GET http://webspilka.dev/autopodbor/TinyMCECodeEditor/PopupForm/forTemplate	
404 Not Found 772ms	
jquery....3783829 (рядок 8240)
"NetworkError: 404 Not Found - http://webspilka.dev/autopodbor/TinyMCECodeEditor/PopupForm/forTemplate"

**Comment by webspilka** [comment]
I find problem
https://docs.silverstripe.org/en/3.2/changelogs/3.2.0/#api-removed-url-routing-by-controller-name
> The auto-routing of controller class names to URL endpoints has been removed (rule: '$Controller//$Action/$ID/$OtherID': '*'). This increases clarity in routing since it makes URL entpoints explicit, and thereby simplifies system and security reviews.

add file /mysite/_config/routes.yml
```yml
---
Name: my-routes
After: framework/routes#coreroutes
---
Director:
  rules:
    '$Controller//$Action/$ID/$OtherID':  '*'
```
its work, but not secure
